### ISSUE TITLE
이온 초기화 없이 프로세스간 통신 오류 메시지 해결 할 수 있는 방법이 있을지 궁금합니다.

### ISSUE THREAD

**Issue by wwfstan** [openpilotusers/openpilot_084#1]
항상 감사합니다!!

아래 상황의 해결책이 있는지 궁금합니다.

이온 초기화 없이 프로세스간 통신 오류 메시지 해결 할 수 있는 방법이 있을지 궁금합니다.

잘 사용하던 OPKR_0.8.4_test를 git pull 이후 인게이지 시
프로세스 간 통신 오류 메시지가 생겼습니다.
해결해보려고
판다플러싱, git reset, 차량 재시동, 최근 올라온 git pull(f680ecad3bf8d4b4baba011ecfb229f3eb5ae0a3)을 해도 프로세스 오류는 그대로 입니다.

opkr 0.8.3로 재부팅하면 문제 없이 인게이지 됩니다.

사실 이런 상황이 081부터 몇 번 있었는데
결국 해결을 못해서 결국 이온 초기화 이후 다시 설치해서 정상 작동을 했던거같습니다.

혹시 이온 초기화 없이 해결 할 수 있는 방법이 있을지 궁금합니다.

감사합니다!!

**Comment by hoyong202** [comment]
사용자 설정 메뉴에 프로세스간 통신오류 알람끄기를 체크하십시오.

**Comment by wwfstan** [comment]
> 사용자 설정 메뉴에 프로세스간 통신오류 알람끄기를 체크하십시오.

답변 감사드립니다.

저도 사용자 설정 메뉴에 프로세스간 통신오류 알람끄기를 체크 기능을 사용해봤지만
여전히 오픈파일럿 인게이지 되지 않고, 프로세스 통신 오류 메시지가 발생했습니다.
